import React, { ReactNode, useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';
import BackToHomeBtn from './buttons/BackToHomeBtn';

interface LayoutProps {
  children?: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  const router = useRouter();
  const [isHomepage, setIsHomepage] = useState(router.pathname === '/');

  useEffect(() => {
    setIsHomepage(router.pathname === '/');
  }, [router.pathname]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.5.1/mapbox-gl.css"
          rel="stylesheet"
        />
      </Head>
      {!isHomepage && <BackToHomeBtn />}

      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>
        <a
          href="https://sandrofi.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image
              src="/sandrofi-logo.svg"
              alt="Sandrofi Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Layout;
