name: Deploy

# Controls when the workflow will run
on:
  # Allows this workflow to be called from another workflow
  workflow_call:
    inputs:
      bucket-name:
        required: true
        type: string
      invalidateCache:
        required: false
        type: boolean
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      mapster-env-production:
        required: true
      distribution-id:
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - name: Create env file for production
        run: |
          touch .env.production
          echo "${{ secrets.mapster-env-production }}" > .env.production
          cat .env.production
      - run: yarn build
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: eu-west-2
      - run: aws s3 sync ./out s3://${{ inputs.bucket-name }} --delete
      - name: Invalidate Cloudfront Cache
        if: inputs.invalidateCache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.distribution-id }} --paths "/*"
